/* Generated by re2c 1.1.1 on Thu Feb  9 17:22:22 2023 */
#line 1 "lexer.re"
#include <iostream>

#include "lexer.hpp"

#include "token.hpp"

namespace SpasmImpl
{
namespace ASM
{
//! Namespace for all lexical analisys classes
namespace Lexer
{

Lexer::Lexer (std::istream & _file, size_t _buffer_size)
: file (&_file), buffer_size (_buffer_size), state (unsigned(-1)),
lineno (0)
{
    buffer = new char[buffer_size];
    cursor = limit = marker = token_start = NULL;
}

Lexer::~Lexer ()
{
    delete [] buffer;
}

bool Lexer::tokenize (TokenStream &ts)
{
#line 43 "lexer.re"
    
    
    
    
    while (1) {
        
        
#line 41 "lexer.cpp"
        {
            char yych;
            if ((limit - cursor) < 7) return true;
            yych = *cursor;
            switch (yych) {
                case 0x00:	goto yy2;
                case '\n':	goto yy6;
                case ' ':	goto yy8;
                case '"':	goto yy11;
                case '#':	goto yy13;
                case '\'':	goto yy15;
                case '-':	goto yy17;
                case '0':	goto yy18;
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':	goto yy20;
                case ':':	goto yy22;
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'b':
                case 'e':
                case 'f':
                case 'h':
                case 'i':
                case 'k':
                case 'n':
                case 'q':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                case 'a':	goto yy27;
                case 'c':	goto yy28;
                case 'd':	goto yy29;
                case 'g':	goto yy30;
                case 'j':	goto yy31;
                case 'l':	goto yy32;
                case 'm':	goto yy33;
                case 'o':	goto yy34;
                case 'p':	goto yy35;
                case 'r':	goto yy36;
                case 's':	goto yy37;
                default:	goto yy4;
            }
        yy2:
            ++cursor;
#line 332 "lexer.re"
            {
                ts.push_token (Token (Token::EndInput, lineno));
                
                break;
            }
#line 128 "lexer.cpp"
        yy4:
            ++cursor;
        yy5:
#line 338 "lexer.re"
            {
                return false;
            }
#line 136 "lexer.cpp"
        yy6:
            ++cursor;
#line 325 "lexer.re"
            {
                ++lineno;
                token_start = cursor;
                
                continue;
            }
#line 146 "lexer.cpp"
        yy8:
            ++cursor;
            if (limit <= cursor) return true;
            yych = *cursor;
            switch (yych) {
                case ' ':	goto yy8;
                default:	goto yy10;
            }
        yy10:
#line 309 "lexer.re"
            {
                token_start = cursor;
                
                continue;
            }
#line 162 "lexer.cpp"
        yy11:
            ++cursor;
            if (limit <= cursor) return true;
            yych = *cursor;
            switch (yych) {
                case '"':	goto yy38;
                case '\\':	goto yy40;
                default:	goto yy11;
            }
        yy13:
            ++cursor;
            if (limit <= cursor) return true;
            yych = *cursor;
            switch (yych) {
                case '\n':	goto yy42;
                default:	goto yy13;
            }
        yy15:
            ++cursor;
            if (limit <= cursor) return true;
            yych = *cursor;
            switch (yych) {
                case '\'':	goto yy38;
                case '\\':	goto yy44;
                default:	goto yy15;
            }
        yy17:
            yych = *++cursor;
            switch (yych) {
                case '0':	goto yy46;
                default:	goto yy5;
            }
        yy18:
            yych = *(marker = ++cursor);
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case ':':	goto yy48;
                case 'X':
                case 'x':	goto yy50;
                default:	goto yy19;
            }
        yy19:
#line 62 "lexer.re"
            {
                ts.push_token (Token (Token::Integer, lineno,
                                      token_start, cursor));
                token_start = cursor;
                
                continue;
            }
#line 222 "lexer.cpp"
        yy20:
            marker = ++cursor;
            if ((limit - cursor) < 2) return true;
            yych = *cursor;
            switch (yych) {
                case '.':	goto yy51;
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':	goto yy20;
                case ':':	goto yy22;
                default:	goto yy19;
            }
        yy22:
            ++cursor;
#line 314 "lexer.re"
            {
                token_start = cursor;
                
                continue;
            }
#line 250 "lexer.cpp"
        yy24:
            ++cursor;
            if (limit <= cursor) return true;
            yych = *cursor;
        yy25:
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy26;
            }
        yy26:
#line 294 "lexer.re"
            {
                ts.push_token (Token (Token::Ident, lineno, token_start,
                                      cursor));
                token_start = cursor;
                
                continue;
            }
#line 331 "lexer.cpp"
        yy27:
            yych = *++cursor;
            switch (yych) {
                case '0':	goto yy52;
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':	goto yy54;
                case 'd':	goto yy56;
                case 'r':	goto yy57;
                default:	goto yy25;
            }
        yy28:
            yych = *++cursor;
            switch (yych) {
                case 'a':	goto yy58;
                case 'o':	goto yy59;
                default:	goto yy25;
            }
        yy29:
            yych = *++cursor;
            switch (yych) {
                case 'i':	goto yy60;
                case 'u':	goto yy61;
                default:	goto yy25;
            }
        yy30:
            yych = *++cursor;
            switch (yych) {
                case 'a':	goto yy62;
                default:	goto yy25;
            }
        yy31:
            yych = *++cursor;
            switch (yych) {
                case 'm':	goto yy63;
                default:	goto yy25;
            }
        yy32:
            yych = *++cursor;
            switch (yych) {
                case 'a':	goto yy64;
                case 'e':	goto yy65;
                default:	goto yy25;
            }
        yy33:
            yych = *++cursor;
            switch (yych) {
                case 'a':	goto yy66;
                case 'o':	goto yy67;
                case 'u':	goto yy68;
                default:	goto yy25;
            }
        yy34:
            yych = *++cursor;
            switch (yych) {
                case 'b':	goto yy69;
                default:	goto yy25;
            }
        yy35:
            yych = *++cursor;
            switch (yych) {
                case 'o':	goto yy70;
                case 'r':	goto yy71;
                case 'u':	goto yy72;
                default:	goto yy25;
            }
        yy36:
            yych = *++cursor;
            switch (yych) {
                case '0':	goto yy73;
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':	goto yy75;
                case 'e':	goto yy77;
                default:	goto yy25;
            }
        yy37:
            yych = *++cursor;
            switch (yych) {
                case 't':	goto yy78;
                case 'u':	goto yy79;
                default:	goto yy25;
            }
        yy38:
            ++cursor;
#line 301 "lexer.re"
            {
                ts.push_token (Token (Token::StringValue, lineno, token_start + 1,
                                      cursor - 1));
                token_start = cursor;
                
                continue;
            }
#line 437 "lexer.cpp"
        yy40:
            ++cursor;
            if (limit <= cursor) return true;
            yych = *cursor;
            switch (yych) {
                case '\\':	goto yy40;
                default:	goto yy11;
            }
        yy42:
            ++cursor;
#line 319 "lexer.re"
            {
                ++lineno;
                token_start = cursor;
                
                continue;
            }
#line 455 "lexer.cpp"
        yy44:
            ++cursor;
            if (limit <= cursor) return true;
            yych = *cursor;
            switch (yych) {
                case '\\':	goto yy44;
                default:	goto yy15;
            }
        yy46:
            ++cursor;
            goto yy19;
        yy47:
            ++cursor;
            if (limit <= cursor) return true;
            yych = *cursor;
        yy48:
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':	goto yy47;
                case ':':	goto yy22;
                default:	goto yy49;
            }
        yy49:
            cursor = marker;
            goto yy19;
        yy50:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':	goto yy80;
                default:	goto yy49;
            }
        yy51:
            yych = *++cursor;
            switch (yych) {
                case '0':	goto yy83;
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':	goto yy85;
                default:	goto yy49;
            }
        yy52:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy53;
            }
        yy53:
#line 86 "lexer.re"
            {
                Token t(Token::Integer, lineno,
                        token_start + 1, cursor);
                t.set_int(-t.value_int());
                ts.push_token(t);
                token_start = cursor;
                continue;
            }
#line 609 "lexer.cpp"
        yy54:
            ++cursor;
            if (limit <= cursor) return true;
            yych = *cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':	goto yy54;
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy53;
            }
        yy56:
            yych = *++cursor;
            switch (yych) {
                case 'd':	goto yy87;
                default:	goto yy25;
            }
        yy57:
            yych = *++cursor;
            switch (yych) {
                case 'r':	goto yy89;
                default:	goto yy25;
            }
        yy58:
            yych = *++cursor;
            switch (yych) {
                case 'l':	goto yy90;
                case 'r':	goto yy91;
                default:	goto yy25;
            }
        yy59:
            yych = *++cursor;
            switch (yych) {
                case 'n':	goto yy92;
                default:	goto yy25;
            }
        yy60:
            yych = *++cursor;
            switch (yych) {
                case 'v':	goto yy93;
                default:	goto yy25;
            }
        yy61:
            yych = *++cursor;
            switch (yych) {
                case 'p':	goto yy95;
                default:	goto yy25;
            }
        yy62:
            yych = *++cursor;
            switch (yych) {
                case 'r':	goto yy97;
                default:	goto yy25;
            }
        yy63:
            yych = *++cursor;
            switch (yych) {
                case 'p':	goto yy98;
                default:	goto yy25;
            }
        yy64:
            yych = *++cursor;
            switch (yych) {
                case 'b':	goto yy100;
                default:	goto yy25;
            }
        yy65:
            yych = *++cursor;
            switch (yych) {
                case 'q':	goto yy101;
                case 's':	goto yy103;
                default:	goto yy25;
            }
        yy66:
            yych = *++cursor;
            switch (yych) {
                case 'r':	goto yy104;
                default:	goto yy25;
            }
        yy67:
            yych = *++cursor;
            switch (yych) {
                case 'b':	goto yy105;
                case 'd':	goto yy106;
                default:	goto yy25;
            }
        yy68:
            yych = *++cursor;
            switch (yych) {
                case 'l':	goto yy108;
                default:	goto yy25;
            }
        yy69:
            yych = *++cursor;
            switch (yych) {
                case 'j':	goto yy110;
                default:	goto yy25;
            }
        yy70:
            yych = *++cursor;
            switch (yych) {
                case 'p':	goto yy112;
                default:	goto yy25;
            }
        yy71:
            yych = *++cursor;
            switch (yych) {
                case 'i':	goto yy114;
                default:	goto yy25;
            }
        yy72:
            yych = *++cursor;
            switch (yych) {
                case 's':	goto yy115;
                default:	goto yy25;
            }
        yy73:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy74;
            }
        yy74:
#line 79 "lexer.re"
            {
                ts.push_token (Token (Token::Integer, lineno,
                                      token_start + 1, cursor));
                token_start = cursor;
                
                continue;
            }
#line 862 "lexer.cpp"
        yy75:
            ++cursor;
            if (limit <= cursor) return true;
            yych = *cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':	goto yy75;
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy74;
            }
        yy77:
            yych = *++cursor;
            switch (yych) {
                case 'a':	goto yy116;
                case 't':	goto yy117;
                default:	goto yy25;
            }
        yy78:
            yych = *++cursor;
            switch (yych) {
                case 'r':	goto yy119;
                default:	goto yy25;
            }
        yy79:
            yych = *++cursor;
            switch (yych) {
                case 'b':	goto yy120;
                default:	goto yy25;
            }
        yy80:
            ++cursor;
            if (limit <= cursor) return true;
            yych = *cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':	goto yy80;
                default:	goto yy82;
            }
        yy82:
#line 95 "lexer.re"
            {
                ts.push_token (Token (Token::XInteger, lineno,
                                      token_start, cursor));
                token_start = cursor;
                
                continue;
            }
#line 990 "lexer.cpp"
        yy83:
            ++cursor;
        yy84:
#line 70 "lexer.re"
            {
                ts.push_token (Token (Token::FloatingPoint,
                                      lineno, token_start,
                                      cursor));
                token_start = cursor;
                
                continue;
            }
#line 1003 "lexer.cpp"
        yy85:
            ++cursor;
            if (limit <= cursor) return true;
            yych = *cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':	goto yy85;
                default:	goto yy84;
            }
        yy87:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy88;
            }
        yy88:
#line 149 "lexer.re"
            {
                ts.push_token (Token (Token::Add, lineno));
                token_start = cursor;
                
                continue;
            }
#line 1097 "lexer.cpp"
        yy89:
            yych = *++cursor;
            switch (yych) {
                case 's':	goto yy122;
                default:	goto yy25;
            }
        yy90:
            yych = *++cursor;
            switch (yych) {
                case 'l':	goto yy124;
                default:	goto yy25;
            }
        yy91:
            yych = *++cursor;
            switch (yych) {
                case 'r':	goto yy126;
                default:	goto yy25;
            }
        yy92:
            yych = *++cursor;
            switch (yych) {
                case 's':	goto yy128;
                default:	goto yy25;
            }
        yy93:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy94;
            }
        yy94:
#line 170 "lexer.re"
            {
                ts.push_token (Token (Token::Div, lineno));
                token_start = cursor;
                
                continue;
            }
#line 1198 "lexer.cpp"
        yy95:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy96;
            }
        yy96:
#line 128 "lexer.re"
            {
                ts.push_token (Token (Token::Dup, lineno));
                token_start = cursor;
                
                continue;
            }
#line 1275 "lexer.cpp"
        yy97:
            yych = *++cursor;
            switch (yych) {
                case 'r':	goto yy129;
                default:	goto yy25;
            }
        yy98:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                case 'f':	goto yy131;
                case 't':	goto yy133;
                default:	goto yy99;
            }
        yy99:
#line 198 "lexer.re"
            {
                ts.push_token (Token (Token::Jump, lineno));
                token_start = cursor;
                
                continue;
            }
#line 1358 "lexer.cpp"
        yy100:
            yych = *++cursor;
            switch (yych) {
                case 'e':	goto yy135;
                default:	goto yy25;
            }
        yy101:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy102;
            }
        yy102:
#line 232 "lexer.re"
            {
                ts.push_token (Token (Token::LessEq, lineno));
                token_start = cursor;
                
                continue;
            }
#line 1441 "lexer.cpp"
        yy103:
            yych = *++cursor;
            switch (yych) {
                case 's':	goto yy136;
                default:	goto yy25;
            }
        yy104:
            yych = *++cursor;
            switch (yych) {
                case 'r':	goto yy138;
                default:	goto yy25;
            }
        yy105:
            yych = *++cursor;
            switch (yych) {
                case 'j':	goto yy140;
                default:	goto yy25;
            }
        yy106:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy107;
            }
        yy107:
#line 177 "lexer.re"
            {
                ts.push_token (Token (Token::Mod, lineno));
                token_start = cursor;
                
                continue;
            }
#line 1536 "lexer.cpp"
        yy108:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy109;
            }
        yy109:
#line 163 "lexer.re"
            {
                ts.push_token (Token (Token::Mul, lineno));
                token_start = cursor;
                
                continue;
            }
#line 1613 "lexer.cpp"
        yy110:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                case 'v':	goto yy142;
                default:	goto yy111;
            }
        yy111:
#line 251 "lexer.re"
            {
                ts.push_token (Token (Token::Obj, lineno));
                token_start = cursor;
                
                continue;
            }
#line 1690 "lexer.cpp"
        yy112:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                case 'r':	goto yy144;
                default:	goto yy113;
            }
        yy113:
#line 115 "lexer.re"
            {
                ts.push_token (Token (Token::Pop, lineno));
                token_start = cursor;
                
                continue;
            }
#line 1767 "lexer.cpp"
        yy114:
            yych = *++cursor;
            switch (yych) {
                case 'n':	goto yy146;
                default:	goto yy25;
            }
        yy115:
            yych = *++cursor;
            switch (yych) {
                case 'h':	goto yy147;
                default:	goto yy25;
            }
        yy116:
            yych = *++cursor;
            switch (yych) {
                case 'd':	goto yy149;
                default:	goto yy25;
            }
        yy117:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy118;
            }
        yy118:
#line 225 "lexer.re"
            {
                ts.push_token (Token (Token::Ret, lineno));
                token_start = cursor;
                
                continue;
            }
#line 1862 "lexer.cpp"
        yy119:
            yych = *++cursor;
            switch (yych) {
                case 'i':	goto yy151;
                default:	goto yy25;
            }
        yy120:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy121;
            }
        yy121:
#line 156 "lexer.re"
            {
                ts.push_token (Token (Token::Sub, lineno));
                token_start = cursor;
                
                continue;
            }
#line 1945 "lexer.cpp"
        yy122:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy123;
            }
        yy123:
#line 263 "lexer.re"
            {
                ts.push_token (Token (Token::ArrSize, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2022 "lexer.cpp"
        yy124:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy125;
            }
        yy125:
#line 218 "lexer.re"
            {
                ts.push_token (Token (Token::Call, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2099 "lexer.cpp"
        yy126:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy127;
            }
        yy127:
#line 257 "lexer.re"
            {
                ts.push_token (Token (Token::CreateArr, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2176 "lexer.cpp"
        yy128:
            yych = *++cursor;
            switch (yych) {
                case 't':	goto yy152;
                default:	goto yy25;
            }
        yy129:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy130;
            }
        yy130:
#line 287 "lexer.re"
            {
                ts.push_token (Token (Token::GetArrEl, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2259 "lexer.cpp"
        yy131:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy132;
            }
        yy132:
#line 191 "lexer.re"
            {
                ts.push_token (Token (Token::JumpF, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2336 "lexer.cpp"
        yy133:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy134;
            }
        yy134:
#line 184 "lexer.re"
            {
                ts.push_token (Token (Token::JumpT, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2413 "lexer.cpp"
        yy135:
            yych = *++cursor;
            switch (yych) {
                case 'l':	goto yy154;
                default:	goto yy25;
            }
        yy136:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy137;
            }
        yy137:
#line 238 "lexer.re"
            {
                ts.push_token (Token (Token::Less, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2496 "lexer.cpp"
        yy138:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy139;
            }
        yy139:
#line 281 "lexer.re"
            {
                ts.push_token (Token (Token::ModArr, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2573 "lexer.cpp"
        yy140:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy141;
            }
        yy141:
#line 269 "lexer.re"
            {
                ts.push_token (Token (Token::ModObj, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2650 "lexer.cpp"
        yy142:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy143;
            }
        yy143:
#line 275 "lexer.re"
            {
                ts.push_token (Token (Token::ObjVal, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2727 "lexer.cpp"
        yy144:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy145;
            }
        yy145:
#line 121 "lexer.re"
            {
                ts.push_token (Token (Token::PopTo, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2804 "lexer.cpp"
        yy146:
            yych = *++cursor;
            switch (yych) {
                case 't':	goto yy156;
                default:	goto yy25;
            }
        yy147:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                case 'r':	goto yy158;
                default:	goto yy148;
            }
        yy148:
#line 109 "lexer.re"
            {
                ts.push_token (Token (Token::Push, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2887 "lexer.cpp"
        yy149:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy150;
            }
        yy150:
#line 135 "lexer.re"
            {
                ts.push_token (Token (Token::Read, lineno));
                token_start = cursor;
                
                continue;
            }
#line 2964 "lexer.cpp"
        yy151:
            yych = *++cursor;
            switch (yych) {
                case 'n':	goto yy160;
                default:	goto yy25;
            }
        yy152:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy153;
            }
        yy153:
#line 204 "lexer.re"
            {
                ts.push_token (Token (Token::Const, lineno));
                token_start = cursor;
                
                continue;
            }
#line 3047 "lexer.cpp"
        yy154:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy155;
            }
        yy155:
#line 245 "lexer.re"
            {
                ts.push_token (Token (Token::Label, lineno));
                token_start = cursor;
                
                continue;
            }
#line 3124 "lexer.cpp"
        yy156:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy157;
            }
        yy157:
#line 142 "lexer.re"
            {
                ts.push_token (Token (Token::Print, lineno));
                token_start = cursor;
                
                continue;
            }
#line 3201 "lexer.cpp"
        yy158:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy159;
            }
        yy159:
#line 103 "lexer.re"
            {
                ts.push_token (Token (Token::PushFrom, lineno));
                token_start = cursor;
                
                continue;
            }
#line 3278 "lexer.cpp"
        yy160:
            yych = *++cursor;
            switch (yych) {
                case 'g':	goto yy161;
                default:	goto yy25;
            }
        yy161:
            yych = *++cursor;
            switch (yych) {
                case '0':
                case '1':
                case '2':
                case '3':
                case '4':
                case '5':
                case '6':
                case '7':
                case '8':
                case '9':
                case 'A':
                case 'B':
                case 'C':
                case 'D':
                case 'E':
                case 'F':
                case 'G':
                case 'H':
                case 'I':
                case 'J':
                case 'K':
                case 'L':
                case 'M':
                case 'N':
                case 'O':
                case 'P':
                case 'Q':
                case 'R':
                case 'S':
                case 'T':
                case 'U':
                case 'V':
                case 'W':
                case 'X':
                case 'Y':
                case 'Z':
                case '_':
                case 'a':
                case 'b':
                case 'c':
                case 'd':
                case 'e':
                case 'f':
                case 'g':
                case 'h':
                case 'i':
                case 'j':
                case 'k':
                case 'l':
                case 'm':
                case 'n':
                case 'o':
                case 'p':
                case 'q':
                case 'r':
                case 's':
                case 't':
                case 'u':
                case 'v':
                case 'w':
                case 'x':
                case 'y':
                case 'z':	goto yy24;
                default:	goto yy162;
            }
        yy162:
#line 211 "lexer.re"
            {
                ts.push_token (Token (Token::String, lineno));
                token_start = cursor;
                
                continue;
            }
#line 3361 "lexer.cpp"
        }
#line 342 "lexer.re"
        
    }
    return true;
}

/*!
 ** Fills up the buffer when neccessary.
 ** Note the buffer is always filled to the maximum, not just the
 ** number of bytes neccessary for the lexer to continue.
 **
 ** \param nbytes        - the number of bytes
 */

void Lexer::buffer_grow (size_t new_size)
{
    char *new_buffer = new char[new_size];
    
    std::copy (buffer, limit, new_buffer);
    
    token_start = new_buffer + (token_start - buffer);
    cursor = new_buffer + (cursor - buffer);
    limit = new_buffer + new_size;
    
    buffer_size = new_size;
    
    delete [] buffer;
    buffer = new_buffer;
}

void Lexer::read (size_t nbytes)
{
    if (token_start + nbytes > limit) { // we need larger buffer
        buffer_grow (token_start - buffer + nbytes);
    }
    
    std::copy (token_start, limit, buffer);
    cursor -= token_start - buffer;
    char *old_limit = limit - (token_start - buffer);
    token_start = buffer;
    
    file->read (old_limit, limit - old_limit);
    if (file->eof ()) {
        auto bytes = file->gcount ();
        std::fill (old_limit + bytes, limit, '\0');
    }
}

void Lexer::buffer_init ()
{
    file->read (buffer, buffer_size);
    if (file->eof ()) {
        auto bytes = file->gcount ();
        std::fill (buffer + bytes, buffer + buffer_size, '\0');
    }
    
    cursor = marker = token_start = buffer;
    limit = buffer + buffer_size;
}


}       // namespace Lexer

}       // namespace ASM
}       // namespace SpasmImpl
